apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
  labels:
    app: kafka
spec:
  kafka:
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
    config:
      log.message.format.version: "2.7"
      log.retention.hours: 168
    storage:
      type: persistent-claim
      size: 5Gi
      class: managed-nfs-storage
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "2"
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 5Gi
      class: managed-nfs-storage

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: video-download-links
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 1
  partitions: 1
  config:
    retention.ms: 604800000  # 7 дней
    segment.bytes: 1073741824  # 1GB

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    strimzi.io/cluster: kafka-cluster