apiVersion: apps/v1
kind: Deployment 
metadata:   
  name: master
  labels:
    app: master
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - image: bakvivas/venom_master_node:latest
          name: master-node
          env: 
            - name: BOT_API_TOKEN
              value: "7718224163:AAFaxncK3Fhwa_w1KZJvDYASxgGKzNK4aHI"
            - name: ADRESS_KAFKA_CLUSTER
              value: "kafka-cluster:9092"
            - name: KAFKA_USERNAME
              value: "user1"
            - name: KAFKA_PASSWORD
              value: "W7CBCR4z9p"

---
apiVersion: v1
kind: Service
metadata: 
  name: master-service
  labels:
    app: kafka
  namespace: kafka
spec:
  type: ClusterIP
  selector:
    app: master
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
