# Включаем SASL_PLAINTEXT для аутентификации
listeners=SASL_PLAINTEXT://0.0.0.0:9092

# Указываем механизм аутентификации SASL
sasl.enabled.mechanisms=PLAIN

# Указываем, что будем использовать PLAIN механизм для SASL
sasl.mechanism.inter.broker.protocol=PLAIN

# Указываем, что будем использовать SASL для аутентификации
security.inter.broker.protocol=SASL_PLAINTEXT

# Указываем путь к файлу JAAS конфигурации для пользователей
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
    username="admin" \
    password="admin-secret" \
    user_user1="user1-secret";
